In [1]:
import pandas as pd
import re

In [2]:
!pwd

/home/sgm/codes/wisdomify/data

In [3]:
ver_0 = pd.read_csv('wisdom2eg_0.tsv', sep='\t')
ver_0

,wisdom,eg_1,eg_2,eg_3,eg_4,eg_5,eg_6,eg_7,eg_8,eg_9,eg_10
0,가는 날이 장날,한 달 전부터 기대하던 소풍날 아침에 굵은 빗방울이 떨어지기 시작했다.,"도서관에 책을 빌리러 갔는데, 오늘부터 공사 중이라 빈손으로 돌아왔다.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,갈수록 태산,청년 실업률이 해마다 증가하면서 취업을 앞둔 사람들의 걱정,연구 과제.,"시험을 앞두고 배가 아픈데, 화장실까지 모두 잠겨 있었다.","오늘 직장을 잃었는데, 집주인이 집세를 올려달라고 한다.",NaN,NaN,NaN,NaN,NaN,NaN
2,꿩 대신 닭,교인대신 만만한 적객 몇을 골라 집어넣을 꾀를 낼 만도 했다,녹차가 없으니 홍차를 마셔야지.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,등잔 밑이 어둡다,나는 옆방에 살면서도 전혀 알지 못했구나.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,소문난 잔치에 먹을 것 없다,맛집이라는 소문을 듣고 일부러 먼길을 달려왔는데 막상 먹어 보니 맛이 없더라.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,핑계 없는 무덤 없다,두 살배기 동생을 괴롭힌 것에도 정당한 이유가 있다는 말이니?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,고래 싸움에 새우 등 터진다,대기업에서 노사 갈등으로 파업을 하면 애꿎은 하청 업체만 피해를 보는 상황,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,서당개 삼 년이면 풍월을 읊는다,나는 어릴 적부터 카센터에서 잡일을 도맡아 하다 보니 이젠 혼자서 자동차 수리도 할...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,원숭이도 나무에서 떨어진다,3회 연속 올림픽 금메달리스트인 그 선수도 이번 경기에서는 실수를 하더라.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,산넘어 산,텐트나 담요 등 구호물자를 노린 약탈이 잇따르고 있다.,일본어 공부는 하면 할수록 더 어려워.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ver_1 = pd.read_csv('egs_koreaUniv_v0.tsv', sep='\t')
ver_1 = ver_1[['wisdom', 'eg']]
ver_1

          wisdom                                                 eg
0         산 넘어 산                                 물론 넘어야 할 산은 아직 많다.
1         산 넘어 산  길이 1ｍ가 넘는 아마존 물고기 피라루크, 열대우림 약초로 만든 전통 약재, '브라...
2         산 넘어 산                      세잔은 이 산에 매료돼 60점이 넘는 연작을 남겼다.
3         산 넘어 산  정부는 새 고시제도 시행시기를 2003년으로 잡고 있으나 실제로 시행되기까지는 넘어...
4         산 넘어 산             부산의 선비가 과거 보러 한양에 갈 때 산과 고개를 몇 개나 넘을까.
..           ...                                                ...
963  핑계 없는 무덤 없다  '어떤 날엔 눈만 감아도 석 자 코가 썩썩 잘려 나갔다 무심코 돌다리를 두드렸다가 ...
964  핑계 없는 무덤 없다       핑계 없는 무덤은 없다고, 자신의 독재에는 정의로운 명분이 있다고도 떠들어댄다.
965  핑계 없는 무덤 없다  경성제국대학은 물론 외국문학과도 무관한 내가 굳이 이 염천에 그의 무덤에까지 찾아간...
966  핑계 없는 무덤 없다                   핑계 없는 무덤 없다고, 속사정을 들여다보면 이유는 있다.
967  핑계 없는 무덤 없다                                    핑계 없는 무덤이 없으니까.

[968 rows x 2 columns]

In [5]:
# there may be better way
for i in range(10):
    wisdom = ver_0.iloc[i]['wisdom']
    ver_0_egs = ver_0.iloc[i].filter(regex='eg_*')
    ver_0_not_nan_egs = ver_0_egs[ver_0_egs.notnull()]
    for eg in ver_0_not_nan_egs:
        ver_1 = ver_1.append({'wisdom': wisdom, 'eg': eg}, ignore_index=True)

In [6]:
ver_1.sort_values(axis=0, inplace=True, by='wisdom')
ver_1.reset_index(drop=True, inplace=True)

In [7]:
ver_1

          wisdom                                                 eg
0       가는 날이 장날                                    하지만 가는 날이 장날이다.
1       가는 날이 장날                              가는 날이 장날인지 날이 몹시 궂었다.
2       가는 날이 장날  고양시에 사는 맹렬 낚시꾼들이 추천한 집. 가는 날이 장날이라고 주인 이수뢰 여사가...
3       가는 날이 장날  '가는 날이 장날'에 비슷한 속담으로 '술 익자 체 장수 지나간다'를 알려주고, '...
4       가는 날이 장날  가는 날이 장날이라고 우리가 이동하는 기간에 중국~몽골 기차가 정비관계로 1주일간 ...
..           ...                                                ...
979  핑계 없는 무덤 없다                                    핑계 없는 무덤 없다지만….
980  핑계 없는 무덤 없다                                     '핑계 없는 무덤 없다?'
981  핑계 없는 무덤 없다                   "변명하지 마. 옛부터 '핑계 없는 무덤 없다'고 했어."
982  핑계 없는 무덤 없다  '어떤 날엔 눈만 감아도 석 자 코가 썩썩 잘려 나갔다 무심코 돌다리를 두드렸다가 ...
983  핑계 없는 무덤 없다                         훗날 나는 참으로 핑계 없는 무덤이 되고 싶다.

[984 rows x 2 columns]

In [8]:
ver_1.to_csv('wisdom2eg_1.tsv')